### ISSUE TITLE
Typo in comparison 

### ISSUE THREAD

**Issue by va7deo** [MiSTer-devel/Template_MiSTer#72]
There appears to be a typo in osd.v on line 134.   

v_cnt_h <= v_cnt <= osd_t;

should be 

v_cnt_h <= v_cnt < osd_t;

**Comment by sorgelig** [comment]
What issue you have from that?

**Comment by va7deo** [comment]
v_cnt_h is a single bit.  v_cnt and osd_t are reg [21:0].   
The comment also says it's pipelining the comparisons and that's not a comparison.

**Comment by birdybro** [comment]
This could be intentional, <= in this context is just a relational operator in synthesis. The left hand bit is what is used for the comparison:

| osd_t | v_cnt[21] | v_cnt_h |
| ----- | --------- | ------- |
| 0     | 0         | 1       |
| 0     | 1         | 1       |
| 1     | 0         | 0       |
| 1     | 1         | 1       |

**Comment by sorgelig** [comment]
First `<=` is assignment. The second `<=` is comparison. Result of comparison is single bit. So there is no errors there.

**Comment by va7deo** [comment]
It's obvious now.
